spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://127.0.0.1:5432/db0
        username: postgres
        password: postgres
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name:  org.postgresql.Driver
        jdbc-url: jdbc:postgresql://127.0.0.1:5432/db1
        username: postgres
        password: postgres
    props:
      sql-show: true
    rules:
      sharding:
        tables:
          tb_user:
            actual-data-nodes: ds0.tb_user
            databaseStrategy:
              none:




logging:
  level:
    test: TRACE
    org.apache.shardingsphere.core.route.SQLLogger: TRACE
